language: go
sudo: required
services:
  - docker

env:
  - DISTRO=centos
  - DISTRO=fedora
  - DISTRO=debian

install: true
script:
  - docker ps -a
  - mkdir -p build/
  - cat ci/${DISTRO}.dockerfile.part ci/common.dockerfile.part > Dockerfile
  - docker build -t journalbeat-${DISTRO}-packaging .
  - docker run -v ${PWD}:/go/src/github.com/mheese/journalbeat:rw journalbeat-${DISTRO}-packaging
  - mv journalbeat journalbeat-${DISTRO}

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Fx7eNZUx/z2U4uoAtrLJ1Bfp60tmUd8216nIMJW6S8CqMaoAc2fmWBOl2z/d54Q7UhccBLQAqk5UG3HswC03PwDE5E8ZSh43/DUcL+AY7Tnyk4sfPwzVR9GdlKULvrVb5YInkpg8H5yRpu4uWes8j8RNICxSs+86LetUe/5W+vKi+EoIDuUP4NqJUUQRxO4QSFBJKGwBhRHCISeTa3VKz+fwIipQMMXT3BMzyJ5gyzBapwpwzjHbMWvxYtyEc1H4WGDxjPAXEkK5IaQLUu/xrC3dByv28+On/ohhF0P6JpAIhUXGNrAxk1ig/um3vwSa8V7FGDiecZg1Z2ejb0QOWYtz0DYyS2Yveb27qCPAofv+tSCcvMi4TGSL/BvY2TXqkNiZXKUZCn/0PWSylupQJQ/v8NccZoc6uoyynK+1nacPd7jL8+xAwdenVb95qLWyB332gzBjdD7blqNjaFIUi18JseiuGrCLHxMftvp06oqvKU6zCK4V9a42fkjRjBMB1UuT67+ZuNnaZSJqMALAv2myCoG2vdrRYan8yXnuNuL2vYmoaYXAIs/cFhVYIVGK6xDoRI5Oj5y+6hjt4OkHltovjtaDrHAvbJvew1izPf9njSuoPisJ7zCjdqw/LMMwNQPMbZmhdEptqtH7Yz11qlOxwFuR4rEFQ1qdAVyDmiI=
  file:
    - journalbeat-${DISTRO}
  on:
    branch: master
    tags: true
